/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/v1hhy13PZv6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Component() {
  return (
    (<main
      className="flex min-h-screen flex-col items-center justify-center bg-gray-100 px-4 py-8 dark:bg-gray-900">
      <div
        className="mx-auto w-full max-w-md rounded-lg bg-white p-6 shadow-lg dark:bg-gray-800">
        <h1 className="mb-6 text-3xl font-bold text-gray-900 dark:text-gray-50">Baptism Days Calculator</h1>
        <form className="space-y-4">
          <div>
            <label
              className="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-400"
              htmlFor="principles-taught">
              Principles Taught
            </label>
            <input
              className="block w-full rounded-md border border-gray-200 border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500 dark:border-gray-800"
              id="principles-taught"
              min="0"
              placeholder="Enter the number of principles taught"
              type="number" />
          </div>
          <div>
            <label
              className="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-400"
              htmlFor="principles-per-visit">
              Principles Taught per Visit
            </label>
            <input
              className="block w-full rounded-md border border-gray-200 border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500 dark:border-gray-800"
              id="principles-per-visit"
              min="0"
              placeholder="Enter the number of principles taught per visit"
              type="number" />
          </div>
          <div>
            <label
              className="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-400"
              htmlFor="days-between-visits">
              Days Between Visits
            </label>
            <input
              className="block w-full rounded-md border border-gray-200 border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500 dark:border-gray-800"
              id="days-between-visits"
              min="0"
              placeholder="Enter the number of days between visits"
              type="number" />
          </div>
          <button
            className="w-full rounded-md bg-blue-500 px-4 py-2 text-white hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-600"
            type="submit">
            Calculate Days to Baptism
          </button>
        </form>
      </div>
      <div
        className="mt-8 w-full max-w-md rounded-lg bg-white p-6 shadow-lg dark:bg-gray-800">
        <h2 className="mb-4 text-2xl font-bold text-gray-900 dark:text-gray-50">Results</h2>
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-gray-700 dark:text-gray-400">Days to Baptism:</span>
            <span className="font-bold text-gray-900 dark:text-gray-50">
              <span id="days-to-baptism">0</span>
              days{"\n"}
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-gray-700 dark:text-gray-400">Visits Remaining:</span>
            <span className="font-bold text-gray-900 dark:text-gray-50">
              <span id="visits-remaining">0</span>
            </span>
          </div>
        </div>
      </div>
    </main>)
  );
}
